apiVersion: v1
kind: Pod
metadata: 
  name: demo-kotlinapp
  labels:
    role: webapp
spec:
  containers:
    - name: web
      image: jsprick14/demo-kotlincreatedbyjon
      ports:
      - containerPort: 80
        name: web
        protocol: TCP